language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
branches:
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: iJF+9uAHZWo4m5Oa93+nYewoYBYOcPNAoFa9huKgw8laCflC5mpz9Mg7u8alKJP+I3ZA95mAw19kpNzeGgyaMChY5D7dXtOQd/5mxB0D4KX4OX80zue/OSDy/Ual40qwkAMh7pU+rIyW/fUPxfRbJSTdyTAN8JusemlAkYt5+9y9ln5uVWsBqBL+i7vvLEpjLUi8fxjEACM91P/yEQrhiRwtfrQnRXtr+qi2jIfWfQGnpTl6E1nDe5588QZJzdyjkPl322OVrwmLHUasCX3r23S6atRDmRxZv4TqssCeUCuhe1XOzyMSrpS927i4iZKnXdotbPce6aYfK5OeJFDg0NT+EaYan8IZbAgFvTGhHNoS0HFdsGhL/G01MsveLhJTrf5ae/meHB6wFEy9veDSjtmgsRzr/WxvXR6+wobjwUHVVi4AKBlgcQ6nTAztGiRUFtqsczsunl3hFZSvg7/0fbCeNlh+cGj9aesF+YfSoWl3zCSHvvLIDtbiHR5IahmTVZGf/JU9YezZU42q55gMGJPktWEKXPzrOA0EEhcMz1uqBEOQqcRB+f4f+bPk7wvx54Ayclm3JRLsuIVePdJ13iCfCzdIiSD4/Lm+dyikox6omVVN3wnvftlZUVQDabtnnMR44R6oa+B/z58gD764c2Veog/7WBYHrSXjmMiudmk=
  - secure: JDesIEZ2qGXQOY6/b8VMDxxmqb2CnjQlWusz+6jKM15KoDhv+qFVeWu0VqGkjmFw1ebjvdGi+p6yrrScLjJ0h7U9NmuGZo6qzHyi1Wyzn2deDAOPEe6AKrqeQmZNwX1OXYWbOHf0kkCN4s49kDL0OhiFaVTEyCyPBVSJNyJ7u5f8P2KJWdqWyI9lJtnoCAan0CEkI+uUu9rpMQq2UGjw2pdFcqMveqKbPbxsVtZ+9cDFZptCF2rLlu4mj/Na9eHeacMgV8z4tzuSytCbrjLh/rRXGIiq8IFs2xchGFfUjHW6c9yxcl+FdveKy32IVaJIUnbBD6t8605Byz560dkzXjK25ddphjilNeIMBvYc1iEJQ9LZw+mBg8cl165ByR7iinZxe8sJoih6P6Fz2dRUw5FOgzTlMieAxAg4FkSjCsf6kB0bZ0PkbAqXALSjOdgo58AIIptJBvEhnW2YTW5O7VAIULEEymouG6rIuVjJ4kqg5f2FpWcGMgITWqy9BLtYug3HWcGDVXLRk/VSNdFT89cm18uFFpcMRZForGa65YwI4P/ozJrPOG5S6BbMssv20SXlu1miDz7dudrByDrzS9LB+CQr0k45/kzYl2Jxx+NwQAB/dw74V9WJIaT90jE2I1jkbqUSBjTiKmdgC8s6qDSutdbVAB8UkoAobXsgNJw=
